/*********************************************************************
HTTP Application callback source file 

Company:
   Microchip Technology Inc. 

File Name:
   http_print.c

Description: 
   Provides callback headers and resolution for user's custom
   HTTP Application.
   
   This file is automatically generated by the MPFS Utility
   ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
   
*********************************************************************/

/*********************************************************************
Copyright (C) 2012-2018 Microchip Technology Inc. and its subsidiaries 
 Microchip Technology Inc. and its subsidiaries.
 Subject to your compliance with these terms, you may use Microchip software
 and any derivatives exclusively with Microchip products. It is your
 responsibility to comply with third party license terms applicable to your
 use of third party software (including open source software) that may
 accompany Microchip software.

 THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
 EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
 WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR
 PURPOSE.
 
 IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
 INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
 WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
 BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
 FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
 ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *********************************************************************/

#include "tcpip/tcpip.h"

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID);
void TCPIP_HTTP_Print_hellomsg(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_builddate(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_version(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_uploadedmd5(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_R(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_freq(HTTP_CONN_HANDLE connHandle);

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID)
{
    TCP_SOCKET sktHTTP; 
    switch(callbackID)
    {
        case 0x00000000:
			TCPIP_HTTP_FileInclude(connHandle,(const uint8_t *)"header.inc");
			break;
        case 0x00000001:
			TCPIP_HTTP_Print_hellomsg(connHandle);
			break;
        case 0x00000002:
			TCPIP_HTTP_FileInclude(connHandle,(const uint8_t *)"footer.inc");
			break;
        case 0x00000006:
			TCPIP_HTTP_Print_builddate(connHandle);
			break;
        case 0x0000000d:
			TCPIP_HTTP_Print_version(connHandle);
			break;
        case 0x0000000e:
			TCPIP_HTTP_Print_led(connHandle,0);
			break;
        case 0x00000013:
			TCPIP_HTTP_Print_uploadedmd5(connHandle);
			break;
        case 0x00000038:
			TCPIP_HTTP_Print_R(connHandle,1);
			break;
        case 0x00000039:
			TCPIP_HTTP_Print_R(connHandle,2);
			break;
        case 0x0000003a:
			TCPIP_HTTP_Print_R(connHandle,3);
			break;
        case 0x0000003b:
			TCPIP_HTTP_Print_R(connHandle,4);
			break;
        case 0x0000003c:
			TCPIP_HTTP_Print_R(connHandle,5);
			break;
        case 0x0000003d:
			TCPIP_HTTP_Print_R(connHandle,6);
			break;
        case 0x0000003e:
			TCPIP_HTTP_Print_R(connHandle,7);
			break;
        case 0x0000003f:
			TCPIP_HTTP_Print_R(connHandle,8);
			break;
        case 0x00000041:
			TCPIP_HTTP_Print_freq(connHandle);
			break;
        default:
            // Output notification for undefined values
            sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
            TCPIP_TCP_ArrayPut(sktHTTP, (const uint8_t *)"!DEF", 4);
    }
    return;
}

void TCPIP_HTTP_Print_myVariable(HTTP_CONN_HANDLE connHandle)
{
    TCP_SOCKET sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
    TCPIP_TCP_Put(sktHTTP, '~');
    return;
}
