<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Cryogenic temperature measurement module web-interface</title>
<link href="mchp.css" rel="stylesheet" type="text/css" />
<script src="mchp.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 65px 5px"><img src="Dialtek-emblema.png" alt="Dialtek" align="left"/><img src="LHEP-emblema.png" alt="LHEP" align="right"/></div>

<div id="title">
<table style="padding-left: 10%; width: 95%; text-align: center;"><tr>
<td>PKT-8</td><td>CRYOGENIC TEMPERATURE MEASUREMENT MODULE</td><td>WEB INTERFACE</td>
</tr></table>
</div>

<div id="menu">
<a href="index.htm">Measurements</a>
<a href="device_settings.htm">Device settings</a>
<a href="coefficients.htm">Coefficients</a>
<a href="network_settings.htm">Network settings</a>
<!--
<a href="index.htm">Overview</a>
<a href="dynvars.htm">Dynamic Variables</a>
<a href="forms.htm">Processing Forms</a>
<a href="auth.htm">Authentication</a>
<a href="cookies.htm">Cookies</a>
<a href="upload.htm">Uploading Files</a>
<a href="email">Sending Emails</a>
<a href="dyndns">Dynamic DNS</a>
<a href="protect/config.htm">Network Configuration</a>
<a href="snmp/snmpconfig.htm">SNMP Configuration</a>
-->
</div>
