# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(425, 400)
        MainWindow.setWindowTitle(_fromUtf8(""))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(5, 380, 411, 16))
        self.progressBar.setMaximum(500)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.Right_b = QtGui.QPushButton(self.centralwidget)
        self.Right_b.setGeometry(QtCore.QRect(195, 100, 90, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Right_b.setFont(font)
        self.Right_b.setObjectName(_fromUtf8("Right_b"))
        self.Left_b = QtGui.QPushButton(self.centralwidget)
        self.Left_b.setGeometry(QtCore.QRect(15, 100, 90, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Left_b.setFont(font)
        self.Left_b.setObjectName(_fromUtf8("Left_b"))
        self.Up_b = QtGui.QPushButton(self.centralwidget)
        self.Up_b.setGeometry(QtCore.QRect(105, 10, 90, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Up_b.setFont(font)
        self.Up_b.setObjectName(_fromUtf8("Up_b"))
        self.Down_b = QtGui.QPushButton(self.centralwidget)
        self.Down_b.setGeometry(QtCore.QRect(105, 190, 90, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Down_b.setFont(font)
        self.Down_b.setObjectName(_fromUtf8("Down_b"))
        self.statusbox = QtGui.QLabel(self.centralwidget)
        self.statusbox.setGeometry(QtCore.QRect(10, 360, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.statusbox.setFont(font)
        self.statusbox.setText(_fromUtf8(""))
        self.statusbox.setObjectName(_fromUtf8("statusbox"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 300, 400, 76))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 25, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 25, 86, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.v_speed = QtGui.QSpinBox(self.groupBox)
        self.v_speed.setGeometry(QtCore.QRect(30, 45, 66, 22))
        self.v_speed.setMaximum(100)
        self.v_speed.setProperty("value", 1)
        self.v_speed.setObjectName(_fromUtf8("v_speed"))
        self.h_speed = QtGui.QSpinBox(self.groupBox)
        self.h_speed.setGeometry(QtCore.QRect(150, 45, 66, 22))
        self.h_speed.setMaximum(100)
        self.h_speed.setProperty("value", 1)
        self.h_speed.setObjectName(_fromUtf8("h_speed"))
        self.v_speed_s = QtGui.QSpinBox(self.groupBox)
        self.v_speed_s.setGeometry(QtCore.QRect(295, 45, 66, 22))
        self.v_speed_s.setMaximum(100)
        self.v_speed_s.setProperty("value", 1)
        self.v_speed_s.setObjectName(_fromUtf8("v_speed_s"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(305, 25, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.l_step = QtGui.QSpinBox(self.centralwidget)
        self.l_step.setGeometry(QtCore.QRect(25, 165, 66, 22))
        self.l_step.setMaximum(5000)
        self.l_step.setProperty("value", 100)
        self.l_step.setObjectName(_fromUtf8("l_step"))
        self.r_step = QtGui.QSpinBox(self.centralwidget)
        self.r_step.setGeometry(QtCore.QRect(210, 165, 66, 22))
        self.r_step.setMaximum(5000)
        self.r_step.setProperty("value", 100)
        self.r_step.setObjectName(_fromUtf8("r_step"))
        self.d_step = QtGui.QSpinBox(self.centralwidget)
        self.d_step.setGeometry(QtCore.QRect(120, 255, 66, 22))
        self.d_step.setMaximum(5000)
        self.d_step.setProperty("value", 100)
        self.d_step.setObjectName(_fromUtf8("d_step"))
        self.u_step = QtGui.QSpinBox(self.centralwidget)
        self.u_step.setGeometry(QtCore.QRect(120, 75, 66, 22))
        self.u_step.setMaximum(5000)
        self.u_step.setProperty("value", 100)
        self.u_step.setObjectName(_fromUtf8("u_step"))
        self.Up_bs = QtGui.QPushButton(self.centralwidget)
        self.Up_bs.setGeometry(QtCore.QRect(320, 20, 90, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Up_bs.setFont(font)
        self.Up_bs.setObjectName(_fromUtf8("Up_bs"))
        self.Down_bs = QtGui.QPushButton(self.centralwidget)
        self.Down_bs.setGeometry(QtCore.QRect(320, 200, 90, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Down_bs.setFont(font)
        self.Down_bs.setObjectName(_fromUtf8("Down_bs"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(5, 0, 291, 291))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 0, 111, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.progressBar.raise_()
        self.Right_b.raise_()
        self.Left_b.raise_()
        self.Up_b.raise_()
        self.Down_b.raise_()
        self.statusbox.raise_()
        self.groupBox.raise_()
        self.l_step.raise_()
        self.r_step.raise_()
        self.d_step.raise_()
        self.u_step.raise_()
        self.Up_bs.raise_()
        self.Down_bs.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.Right_b.setText(_translate("MainWindow", "--->", None))
        self.Left_b.setText(_translate("MainWindow", "<---", None))
        self.Up_b.setText(_translate("MainWindow", "Вверх", None))
        self.Down_b.setText(_translate("MainWindow", "Вниз", None))
        self.groupBox.setTitle(_translate("MainWindow", "Скорость передвижения", None))
        self.label.setText(_translate("MainWindow", "Вертикаль К", None))
        self.label_2.setText(_translate("MainWindow", "Горизонталь К", None))
        self.label_5.setText(_translate("MainWindow", "Шприц", None))
        self.Up_bs.setText(_translate("MainWindow", "Вверх", None))
        self.Down_bs.setText(_translate("MainWindow", "Вниз", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Капилляр", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Шприц", None))

